[tool.poetry]
name = "mimiqlink"
version = "0.2.0"
description = ""
authors = ["QPerfect <guido.masella@qperfect.io>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"
requests = "^2.28.2"
flask = "^2.2.3"


[tool.poetry.group.test.dependencies]
pytest = "^7.3.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
