[tool.poetry]
name = "mimiqlink"
version = "0.1.2"
description = ""
authors = ["Guido Masella <guido.masella@gmail.com>", "Vase Moeini <vmoeini@unistra.fr>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
requests = "^2.28.2"
flask = "^2.2.3"


[tool.poetry.group.test.dependencies]
pytest = "^7.3.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
